[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{% if version %}\
    # {{ version | trim_start_matches(pat="v") }}\n
    {% if previous %}\
        {% if previous.version %}\
            \n**Full Changelog:** [{{ previous.version }}...{{ version }}]\
                (https://github.com/nyx-team/nyx/compare/{{ previous.version }}...{{ version }})\
        {% else %}
            \n**Full Changelog:** [{{ version }}](https://github.com/nyx-team/nyx/tree/{{ version }})\
        {% endif %}
    {% endif %}
{% else %}\
    ## [Unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ## {{ group | upper_first }}
    {% for commit in commits %}
        - {% if commit.scope %}**{{ commit.scope }}:**{% endif %} \
          {{ commit.message | upper_first }} \
          ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/nyx-team/nyx/commit/{{ commit.id }}))\
          {% if commit.breaking %}\
            {% for breakingChange in commit.footers %}\
                \n{% raw %} {% endraw %}- **{{ breakingChange.token }}{{ breakingChange.separator }}** {{ breakingChange.value }}\
            {% endfor %}
          {% endif %}\
    {% endfor %}
{% endfor %}
"""
trim = true
footer = "\n"

[git]
conventional_commits = true
filter_unconventional = false

commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^perf", group = "Performance"},
    { message = "^refactor", group = "Refactor"},
    { message = "^test", group = "Testing"},
    { message = "^chore", skip = true },
    { message = "^command", skip = true },
    { message = "^ci", skip = true },
]
filter_commits = false
tag_pattern = "v[0-9]*|[0-9]*"
skip_tags = ""
topo_order = false
sort_commits = "newest"
