export const PermissionsReadable = {
  CREATE_INSTANT_INVITE: 'Create Invite',
  KICK_MEMBERS: 'Kick Members',
  BAN_MEMBERS: 'Ban Members',
  ADMINISTRATOR: 'Administrator',
  MANAGE_CHANNELS: 'Manage Channels',
  MANAGE_GUILD: 'Manage Guild',
  ADD_REACTIONS: 'Add Reactions',
  VIEW_AUDIT_LOG: 'View Audit Log',
  PRIORITY_SPEAKER: 'Priority Speaker',
  STREAM: 'Video',
  VIEW_CHANNEL: 'View Channel',
  SEND_MESSAGES: 'Send Messages',
  SEND_TTS_MESSAGES: 'Send Text-to-speech messages',
  MANAGE_MESSAGES: 'Manage Messages',
  EMBED_LINKS: 'Embed Links',
  ATTACH_FILES: 'Attach Files',
  READ_MESSAGE_HISTORY: 'Read Message History',
  MENTION_EVERYONE: 'Mention Everyone',
  USE_EXTERNAL_EMOJIS: 'Use External Emojis',
  VIEW_GUILD_INSIGHTS: 'View Server Insights',
  CONNECT: 'Connect',
  SPEAK: 'Speak',
  MUTE_MEMBERS: 'Mute Members',
  DEAFEN_MEMBERS: 'Deafen Members',
  MOVE_MEMBERS: 'Move Members',
  USE_VAD: 'Use Voice Activity',
  CHANGE_NICKNAME: 'Change Nickname',
  MANAGE_NICKNAMES: 'Manage Nicknames',
  MANAGE_ROLES: 'Manage Roles',
  MANAGE_WEBHOOKS: 'Manage Webhooks',
  MANAGE_EMOJIS_AND_STICKERS: 'Manage Emojis and Stickers',
  USE_APPLICATION_COMMANDS: 'Use Application Commands',
  REQUEST_TO_SPEAK: 'Request to Speak',
  MANAGE_THREADS: 'Manage Threads',
  USE_PUBLIC_THREADS: 'Use Public Threads',
  CREATE_PUBLIC_THREADS: 'Create Public Threads',
  USE_PRIVATE_THREADS: 'Use Private Threads',
  CREATE_PRIVATE_THREADS: 'Create Private Threads',
  USE_EXTERNAL_STICKERS: 'Use External Stickers',
  SEND_MESSAGES_IN_THREADS: 'Send Messages in Threads',
  START_EMBEDDED_ACTIVITIES: 'Use Activities',
  MODERATE_MEMBERS: 'Moderate Members',
  MANAGE_EVENTS: 'Manage Events',
};
